# Generated by Django 4.2.16 on 2026-01-14 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConsolidationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nom de la configuration', max_length=255)),
                ('output_filename', models.CharField(default='Consolidation', help_text='Nom du fichier de sortie', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('selected_sheets', models.JSONField(default=list, help_text='Liste des feuilles sélectionnées')),
            ],
            options={
                'verbose_name': 'Configuration de Consolidation',
                'verbose_name_plural': 'Configurations de Consolidation',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ExcelConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='BP 2026', max_length=255)),
                ('config_json', models.JSONField(default=dict)),
                ('prompt', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Configuration Excel',
                'verbose_name_plural': 'Configurations Excel',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Responsable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nom du responsable', max_length=255)),
                ('order', models.IntegerField(default=0, help_text="Ordre d'affichage")),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsables', to='excel_creator.consolidationconfig')),
            ],
            options={
                'verbose_name': 'Responsable',
                'verbose_name_plural': 'Responsables',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nom du site (modifiable)', max_length=255)),
                ('original_filename', models.CharField(help_text='Nom original du fichier', max_length=255)),
                ('file_path', models.CharField(blank=True, help_text='Chemin du fichier uploadé', max_length=500, null=True)),
                ('order', models.IntegerField(default=0, help_text="Ordre d'affichage")),
                ('detected_sheets', models.JSONField(default=list, help_text='Feuilles détectées dans le fichier')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sites', to='excel_creator.responsable')),
            ],
            options={
                'verbose_name': 'Site',
                'verbose_name_plural': 'Sites',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SiteSheetConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet_name', models.CharField(help_text='Nom de la feuille', max_length=255)),
                ('col_start', models.CharField(default='A', help_text='Colonne de début', max_length=5)),
                ('col_end', models.CharField(default='Z', help_text='Colonne de fin', max_length=5)),
                ('row_start', models.IntegerField(default=1, help_text='Ligne de début')),
                ('row_end', models.IntegerField(default=100, help_text='Ligne de fin')),
                ('is_selected', models.BooleanField(default=True, help_text='Feuille sélectionnée pour extraction')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sheet_configs', to='excel_creator.site')),
            ],
            options={
                'verbose_name': 'Configuration de Feuille',
                'verbose_name_plural': 'Configurations de Feuilles',
                'ordering': ['sheet_name'],
                'unique_together': {('site', 'sheet_name')},
            },
        ),
    ]
